### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by AdhamNasr** [Lissy93/portainer-templates#1]
There are a few duplicates in the list, I'll either list them here for you, or dive into the source code and edit them later if you don't mind :)

**Comment by Lissy93** [comment]
Thanks @AdhamNasr :)
I've pushed an update in d3fb62828d7606663276e3cb99bf8e7c533377ea which better removes duplicates (I _think_ all of them, except where configs are very different).
Right now, the order of the sources determines which template will take president, maybe there's a better method?

**Comment by AdhamNasr** [comment]
Not sure if there is, I couldn't check the sourcecode this weekend, but I'll try to squeeze sometime in and get back to you as soon as I can 😊
