### ISSUE TITLE
No wordpress in last 3 commits

### ISSUE THREAD

**Issue by wikoga** [Lissy93/portainer-templates#10]
Last one I can use for wordpress is the one in 28-May-2023 - (https://github.com/Lissy93/portainer-templates/commit/f985b6d7fb09f76280bcc752eb9b80c0f3c57250)

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
