### ISSUE TITLE
InvoiceNinja Template is a major version out of date

### ISSUE THREAD

**Issue by ZachHandley** [Lissy93/portainer-templates#20]
The current is v5, it's v4, not the end of the world but I figured I should put it here, was hoping you had v5 cause I'm having trouble getting Nginx setup behind Traefik but yeah. If you do figure it out, please ping me!

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
