### ISSUE TITLE
Authentik deployment error `while interpolating services.postgresql.environment.[]: required variable PG_PASS is missing a value`

### ISSUE THREAD

**Issue by HammyHavoc** [Lissy93/portainer-templates#23]
I'm attempting to deploy Authentik. When I `Deploy the stack` via the template, I get the following deployment error:

`failed to deploy a stack: time="2024-01-02T02:24:00Z" level=warning msg="The \"PG_PASS\" variable is not set. Defaulting to a blank string." parsing /data/compose/10/7a8b826cc7ab28a33f4b8c8f127877d4404b9a50/Template/Stack/authentik.yml: error while interpolating services.postgresql.environment.[]: required variable PG_PASS is missing a value: database password required`

I'm new to Portainer, but I already realize that unlike Unraid, not all the expected fields are appearing. I only get the following:

- Name
- PUID
- PGID
- PORT

Though unlike Unraid, I can't see how the missing field(s) would be added.

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
