### ISSUE TITLE
Kiwix error on deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#30]
When I try to deploy a Kiwix stack from App Templates, I get this error:

```
Deployment error
failed to deploy a stack: parsing /data/compose/4/51e04cdd91cdec9e3e926519fa1b2914fe7902d9/Template/Stack/kiwix.yml: yaml: line 10: did not find expected alphabetic or numeric character
```

**Comment by shmolf** [comment]
Unfortunately, that template configuration is maintained by [another repository](https://github.com/Lissy93/portainer-templates/blob/15c4f0765af78ef2410ef570bce9263966a71420/templates.json#L4694).

This project aggregates and consolidates various other template-repos, into a single library.

The repository where Kiwix is implemented does not have Issues enabled though. 😢

[Point of failure](https://github.com/xneo1/portainer_templates/blob/51e04cdd91cdec9e3e926519fa1b2914fe7902d9/Template/Stack/kiwix.yml#L10)

Maybe the glob-pattern is supported in new versions of Docker... I don't really know if this syntax is valid for any version of Docker/Portainer. Just speculating
