### ISSUE TITLE
Miniflux error on deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#31]
When I try to deploy a Miniflux stack from App Templates, I get this error:
`Waiting Container Miniflux-DB Error dependency failed to start: container Miniflux-DB is unhealthy`

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
