### ISSUE TITLE
Excalidraw error on deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#33]
When I try to deploy an Excalidraw stack from App Templates, I get this error:
`failed to deploy a stack: listing workers for Build: failed to list workers: Unavailable: connection error: desc = "error reading server preface: http2: frame too large"`

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
