### ISSUE TITLE
Immich broken after initial deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#36]
After successful deploy of an Immich stack from App Templates, the website displays this error:

```
getaddrinfo ENOTFOUND immich-server (ENOTFOUND)

Stacktrace
Error: getaddrinfo ENOTFOUND immich-server
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
```
![image](https://github.com/Lissy93/portainer-templates/assets/58707896/71cfdb99-5497-4295-83ea-d11d1740ae7b)

The `immich-web` container displays this error:
```
Listening on 0.0.0.0:3000
[hooks.server.ts]:handleError getaddrinfo ENOTFOUND immich-server
```

The `immich_proxy` container displays no log entries.

**Comment by bannert1337** [comment]
#7

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
