### ISSUE TITLE
Servas error on deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#37]
When I try to deploy a Servas stack from App Templates, I get this error:
`failed to deploy a stack: stat /data/compose/14/51e04cdd91cdec9e3e926519fa1b2914fe7902d9/Template/Stack/servas.yml: no such file or directory`

**Comment by grand-lotus-iroh** [comment]
```
portainer stack deploy error failed to deploy a stack: stat /data/compose/3/Template/Stack/servas.yml: no such file or directory
```

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
