### ISSUE TITLE
NocoDB error on deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#42]
When I try to deploy a NocoDB stack from App Templates, I get this error:
```unable to fetch git repository id: failed to list repository refs: Get "https://github.com/xneo1/portainer_templates/info/refs?service=git-upload-pack": context deadline exceeded```

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
