### ISSUE TITLE
Grocy error on deploy

### ISSUE THREAD

**Issue by HammyHavoc** [Lissy93/portainer-templates#43]
`Failure
No such image: linuxserver/grocy:latest`

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
