### ISSUE TITLE
Huggin source incorrect

### ISSUE THREAD

**Issue by Koliera** [Lissy93/portainer-templates#45]
Believe it should have the additional link ghcr.io/ as the current template fails.

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.
