### ISSUE TITLE
Port 3000-3001 bei wireshark and homepage konflikt? 

### ISSUE THREAD

**Issue by sk2eu** [Lissy93/portainer-templates#53]
HI
i install portainer via ADD template ... assign the ports from the free area via 50000-50001 and after creating it the only thing this template does... is to continue hammering on the 3000 port? what is going wrong here?

![grafik](https://github.com/Lissy93/portainer-templates/assets/48036204/ab3b129b-1cd6-4e87-9572-1dac688460c8)

nginx: [emerg] bind() to [::]:3000 failed (98: Address in use)

nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address in use)

nginx: [emerg] bind() to [::]:3000 failed (98: Address in use)

nginx: [emerg] still could not bind()

nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address in use)

nginx: [emerg] bind() to [::]:3000 failed (98: Address in use)

**Comment by Lissy93** [comment]
Hey @sk2eu - You need to raise this upstream, I don't write the individual templates, just curate them into a single source.
https://github.com/Lissy93/portainer-templates#raising-issues
