### ISSUE TITLE
Addition to Category > Operating System

### ISSUE THREAD

**Issue by Doocter** [Lissy93/portainer-templates#54]
Can you add Debian and Kali to the Operating systems category

**Comment by shmolf** [comment]
The categories are dynamically assembled from the different [Template sources](https://github.com/Lissy93/portainer-templates/blob/main/sources.csv).

[Example](https://github.com/shmolf/portainer-templates/blob/44e2b9ec734d3e7c6fb708eb4dd81c0a60ca7dd0/templates-2.0.json#L8)

Once a template uses the `Operating Systems` category, the option will appear.
